[package]
name = "spade"
version = "0.1.0"
authors = ["Stefan Altmayer <stoeoef@gmail.com>"]
license="Apache-2.0"
description="Spatial datastructures like r-trees and delaunay triangulations for rust."
homepage=""
repository=""

[dependencies]
cgmath = "0.11.*"
num = "0.1.30"
nalgebra = "0.9.*"

[dev-dependencies]
rand = "0.3.13"
time = "0.1"
glium = "*"

[profile.bench]
opt-level = 3
debug = true
debug-assertions = false

[profile.release]
opt-level = 3
debug = true
debug-assertions = false