[package]
name = "rtree"
version = "0.1.0"
authors = ["Stefan Altmayer <stoeoef@gmail.com>"]

[dependencies]
cgmath = "0.9.1"
num = "0.1.30"

[dev-dependencies]
rand = "0.3.13"
time = "0.1"
glium = "*"

[profile.bench]
opt-level = 3
debug = true
debug-assertions = false

[profile.release]
opt-level = 3
debug = true
debug-assertions = false