[package]
name = "nninterpolation"
version = "0.1.0"

[[bin]]
name = "nninterpolation"

[dependencies]
cgmath = "*"
nalgebra = "*"
noise = "*"
kiss3d = "*"
rand = "*"
spade = { path = "../../" }

[profile.dev]
opt-level = 3