[package]
name = "nninterpolation"
version = "0.1.0"

[[bin]]
name = "nninterpolation"

[dependencies]
cgmath = "*"
nalgebra = "*"
noise = "0.2.*"
kiss3d = "0.13.*"
glfw = "0.19"
rand = "*"
spade = { path = "../../" }

[profile.dev]
opt-level = 3